name: Deploy Android Stage

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: false
        default: ''

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: extract keystore
      env: 
        KEYSTORE: ${{ secrets.KEYSTORE }}
      run: echo $KEYSTORE | base64 --decode > ./app/keystore.jks
    - name: extract keystore properties
      env:
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: echo "$KEYSTORE_PROPERTIES" > ./app/keystore.properties
    - name: extract supply key
      env:
        SUPPLY_KEY: ${{ secrets.PLAYSTORE_DREIPOL }}
      run: echo "$SUPPLY_KEY" > ./app/fastlane/supplyKey.json
    - name: setup ruby version
      uses: actions/setup-ruby@v1
      with: 
        ruby-version: '2.6'
    - name: install bundler
      run: gem install bundler:2.2.1
    - name: Run fastlane
      env:
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK }}
      run: |
          cd app
          bundle install --jobs 2
          bundle exec fastlane stage auto_increment: true slack_url: "$SLACK_URL" message:"${{github.event.inputs.release_notes}}"
    - name: configure git
      run: |
        git config --global user.name 'github ci'
        git config --global user.email 'dev@dreipol.ch'
    - name: commit and push changes
      run: |
        git commit -am "Set new versionCode"
        git push origin HEAD
    - name: create tag
      run: |
        versionCode=$(grep -o 'versionCode\s[0-9]*' ./app/build.gradle | tr -dc '0-9')
        tagname="android_$versionCode"
        git tag $tagname
        git push origin $tagname HEAD
